import numpy as np
from typing import Optional, Tuple
from lut_generator_stepwise import LUT3DGeneratorStepwise
import os


class LUTExporter:
    """3D LUT文件导出器"""

    def __init__(self, lut_generator: LUT3DGeneratorStepwise):
        """
        初始化LUT导出器

        Args:
            lut_generator: 已生成LUT数据的LUT3DGenerator实例
        """
        self.lut_generator = lut_generator
        self.lut_data = lut_generator.lut_data

        if self.lut_data is None:
            raise ValueError("LUT数据为空，请先生成LUT数据")

    def export_cube(self, filename: str, title: str = "Generated 3D LUT"):
        """
        导出为Adobe .cube格式文件

        Args:
            filename: 输出文件名
            title: LUT标题
        """
        print(f"导出CUBE格式LUT到: {filename}")

        with open(filename, 'w') as f:
            # 写入文件头
            f.write(f'TITLE "{title}"\n')
            f.write(f'LUT_3D_SIZE {self.lut_generator.lut_size}\n')
            f.write(f'\n')

            # 按标准顺序写入LUT数据 (R, G, B)
            lut_size = self.lut_generator.lut_size

            for b in range(lut_size):
                for g in range(lut_size):
                    for r in range(lut_size):
                        color = self.lut_data[b, g, r]
                        # 写入RGB值，保留6位小数
                        f.write(f"{color[0]:.6f} {color[1]:.6f} {color[2]:.6f}\n")

        print(f"CUBE文件导出完成: {os.path.abspath(filename)}")

    def export_3dl(self, filename: str, title: str = "Generated 3D LUT"):
        """
        导出为.3dl格式文件

        Args:
            filename: 输出文件名
            title: LUT标题
        """
        print(f"导出3DL格式LUT到: {filename}")

        with open(filename, 'w') as f:
            # 写入文件头
            f.write(f'# {title}\n')
            f.write(f'# Generated by 3D LUT Creator\n')
            f.write(f'# LUT Size: {self.lut_generator.lut_size}\n')
            f.write('\n')

            lut_size = self.lut_generator.lut_size

            # 写入网格尺寸信息
            f.write(f'{lut_size} {lut_size} {lut_size}\n')

            # 写入LUT数据
            for b in range(lut_size):
                for g in range(lut_size):
                    for r in range(lut_size):
                        color = self.lut_data[b, g, r]
                        # 转换为0-1范围
                        r_val = color[0]
                        g_val = color[1]
                        b_val = color[2]
                        f.write(f"{r_val:.6f} {g_val:.6f} {b_val:.6f}\n")

        print(f"3DL文件导出完成: {os.path.abspath(filename)}")

    def export_dat(self, filename: str, title: str = "Generated 3D LUT"):
        """
        导出为.dat格式文件 (DaVinci Resolve格式)

        Args:
            filename: 输出文件名
            title: LUT标题
        """
        print(f"导出DAT格式LUT到: {filename}")

        with open(filename, 'w') as f:
            # 写入文件头
            f.write(f'{title}\n')
            f.write(f'3DMESH\n')
            f.write(f'{self.lut_generator.lut_size}\n')

            lut_size = self.lut_generator.lut_size

            # 写入LUT数据 (每个颜色值一行)
            for b in range(lut_size):
                for g in range(lut_size):
                    for r in range(lut_size):
                        color = self.lut_data[b, g, r]
                        # 转换为0-1范围
                        r_val = color[0]
                        g_val = color[1]
                        b_val = color[2]
                        f.write(f"{r_val:.6f} {g_val:.6f} {b_val:.6f}\n")

        print(f"DAT文件导出完成: {os.path.abspath(filename)}")

    def export_numpy(self, filename: str):
        """
        导出为NumPy二进制格式

        Args:
            filename: 输出文件名
        """
        print(f"导出NumPy格式LUT到: {filename}")

        np.save(filename, self.lut_data)
        print(f"NumPy文件导出完成: {os.path.abspath(filename)}")

    def export_image_preview(self, filename: str, size: Tuple[int, int] = (512, 512)):
        """
        导出LUT预览图像 (颜色网格可视化)

        Args:
            filename: 输出图像文件名
            size: 图像尺寸
        """
        try:
            from PIL import Image

            print(f"生成LUT预览图像: {filename}")

            lut_size = self.lut_generator.lut_size
            width, height = size

            # 创建预览图像
            preview = Image.new('RGB', size)
            pixels = preview.load()

            # 在图像中显示LUT网格
            grid_size = min(width, height) // lut_size

            for b in range(lut_size):
                for g in range(lut_size):
                    for r in range(lut_size):
                        color = self.lut_data[b, g, r]
                        # 转换为0-255范围
                        r_val = int(color[0] * 255)
                        g_val = int(color[1] * 255)
                        b_val = int(color[2] * 255)

                        # 计算在预览图像中的位置
                        x = (r * grid_size) % width
                        y = ((g * lut_size + b) * grid_size) % height

                        # 填充网格单元
                        for dx in range(min(grid_size, width - x)):
                            for dy in range(min(grid_size, height - y)):
                                pixels[x + dx, y + dy] = (r_val, g_val, b_val)

            preview.save(filename)
            print(f"预览图像保存完成: {os.path.abspath(filename)}")

        except ImportError:
            print("警告: PIL库未安装，无法生成预览图像")

    def export_all_formats(self, base_filename: str, title: str = "Generated 3D LUT"):
        """
        导出所有支持的格式

        Args:
            base_filename: 基础文件名 (不含扩展名)
            title: LUT标题
        """
        print("开始导出所有格式...")

        # 创建输出目录
        os.makedirs(os.path.dirname(base_filename) if os.path.dirname(base_filename) else ".", exist_ok=True)

        try:
            self.export_cube(f"{base_filename}.cube", title)
        except Exception as e:
            print(f"CUBE格式导出失败: {e}")

        try:
            self.export_3dl(f"{base_filename}.3dl", title)
        except Exception as e:
            print(f"3DL格式导出失败: {e}")

        try:
            self.export_dat(f"{base_filename}.dat", title)
        except Exception as e:
            print(f"DAT格式导出失败: {e}")

        try:
            self.export_numpy(f"{base_filename}.npy")
        except Exception as e:
            print(f"NumPy格式导出失败: {e}")

        try:
            self.export_image_preview(f"{base_filename}_preview.png")
        except Exception as e:
            print(f"预览图像导出失败: {e}")

        print("所有格式导出完成!")
